module.exports = {
    "login": "mugan86",
    "id": 5081970,
    "node_id": "MDQ6VXNlcjUwODE5NzA=",
    "avatar_url": "https://avatars0.githubusercontent.com/u/5081970?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mugan86",
    "html_url": "https://github.com/mugan86",
    "followers_url": "https://api.github.com/users/mugan86/followers",
    "following_url": "https://api.github.com/users/mugan86/following{/other_user}",
    "gists_url": "https://api.github.com/users/mugan86/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mugan86/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mugan86/subscriptions",
    "organizations_url": "https://api.github.com/users/mugan86/orgs",
    "repos_url": "https://api.github.com/users/mugan86/repos",
    "events_url": "https://api.github.com/users/mugan86/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mugan86/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Anartz Mugika Ledo",
    "company": "@servirace @CrazyWords ",
    "blog": "https://twitter.com/mugan86",
    "location": "Soraluze (Basque Country) (EU)",
    "email": null,
    "hireable": true,
    "bio": "Android Native Developer / Applications hybrid with Ionic (1-3) and Web Developer in Angular 2-7 .\r\nFounder @servirace. Learning Kotlin Android intenselly.",
    "public_repos": 94,
    "public_gists": 2,
    "followers": 10,
    "following": 30,
    "created_at": "2013-07-24T14:28:55Z",
    "updated_at": "2018-11-28T16:18:41Z"

};