module.exports = {

    "login": "usainzg",
    "id": 6026143,
    "node_id": "MDQ6VXNlcjYwMjYxNDM=",
    "avatar_url": "https://avatars3.githubusercontent.com/u/6026143?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/usainzg",
    "html_url": "https://github.com/usainzg",
    "followers_url": "https://api.github.com/users/usainzg/followers",
    "following_url": "https://api.github.com/users/usainzg/following{/other_user}",
    "gists_url": "https://api.github.com/users/usainzg/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/usainzg/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/usainzg/subscriptions",
    "organizations_url": "https://api.github.com/users/usainzg/orgs",
    "repos_url": "https://api.github.com/users/usainzg/repos",
    "events_url": "https://api.github.com/users/usainzg/events{/privacy}",
    "received_events_url": "https://api.github.com/users/usainzg/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Unai Sainz de la Maza",
    "company": null,
    "blog": "https://usainzg.github.io/",
    "location": "Basque Country",
    "email": null,
    "hireable": true,
    "bio": null,
    "public_repos": 21,
    "public_gists": 0,
    "followers": 15,
    "following": 8,
    "created_at": "2013-11-24T22:54:49Z",
    "updated_at": "2018-11-26T16:21:01Z"

};